services:
  - type: web
    name: patent-forge-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERPAPI_KEY
        sync: false

databases:
  - name: patent-forge-db
    databaseName: patent_forge
    user: patent_forge
